

package quanlibanhang;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.*;
import java.sql.Connection;

public class JFTaoDonHang extends javax.swing.JFrame {
 
    public static int pos =0;
    public JFTaoDonHang() {
        initComponents();
        //xử lí thời gian.
        LocalDateTime time = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        thoiGian.setText(time.format(formatter));
        
    }
    public void addSanPham(String maSp ,String lo, String soLuong){
        Connection conn ;
        String traVeTenSanPham = null;
        String traVeDonGia = null;
        double thanhTien = 0;
        try {
            conn = DBConnect.getConnection();
            Statement stmt = conn.createStatement();
            String sql ="SELECT * FROM quanlisanpham WHERE maSanPham ='"+maSp +"'";
            
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {                
                traVeTenSanPham = rs.getString("tenSanPham");
                traVeDonGia = rs.getString("donGia");
                thanhTien = (Double.parseDouble(traVeDonGia)) * (Double.parseDouble(soLuong));
            }
            conn.close();
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
                Logger.getLogger(JFTaoDonHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        DefaultTableModel model = (DefaultTableModel) this.tableSanPham.getModel();
        model.addRow(new Object[]{txtMaDonHang.getText() ,maSp,lo,traVeTenSanPham, soLuong ,traVeDonGia , thanhTien});

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaDonHang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        thoiGian = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        txtTongTien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonThanhToan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLoSanPham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        themSanPhamVaoBang = new javax.swing.JButton();
        xoaSanPham = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        buttonChinhSua = new javax.swing.JButton();
        buttonXemLichSuBan = new javax.swing.JButton();
        buttonSuaDonHang = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÍ CỬA HÀNG");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã đơn hàng:");

        txtMaDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDonHangActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày tạo:");

        thoiGian.setText("timeLocal");
        thoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoiGianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaDonHang)
                    .addComponent(jLabel2)
                    .addComponent(thoiGian)))
        );

        buttonOK.setBackground(new java.awt.Color(51, 255, 0));
        buttonOK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonOK.setForeground(new java.awt.Color(255, 0, 0));
        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đơn hàng:", "Mã sản phẩm", "Lô", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSanPham);

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTongTien.setText("..........");
        txtTongTien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setBackground(new java.awt.Color(0, 255, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("TỔNG TIỀN:");

        buttonThanhToan.setBackground(new java.awt.Color(0, 255, 204));
        buttonThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonThanhToan.setText("THANH TOÁN.");
        buttonThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThanhToanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã sản phẩm:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Lô:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng:");

        themSanPhamVaoBang.setBackground(new java.awt.Color(102, 255, 153));
        themSanPhamVaoBang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        themSanPhamVaoBang.setText("Thêm");
        themSanPhamVaoBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSanPhamVaoBangActionPerformed(evt);
            }
        });

        xoaSanPham.setBackground(new java.awt.Color(102, 255, 153));
        xoaSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        xoaSanPham.setText("Xóa");
        xoaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaSanPhamActionPerformed(evt);
            }
        });

        buttonExit.setBackground(new java.awt.Color(255, 0, 0));
        buttonExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setText("EXIT");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonChinhSua.setBackground(new java.awt.Color(102, 255, 153));
        buttonChinhSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonChinhSua.setText("Chỉnh lại");
        buttonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChinhSuaActionPerformed(evt);
            }
        });

        buttonXemLichSuBan.setBackground(new java.awt.Color(130, 250, 202));
        buttonXemLichSuBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonXemLichSuBan.setText("Xem lịch sử bán");
        buttonXemLichSuBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXemLichSuBanActionPerformed(evt);
            }
        });

        buttonSuaDonHang.setBackground(new java.awt.Color(153, 255, 204));
        buttonSuaDonHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSuaDonHang.setText("Sửa Đơn Hàng.");
        buttonSuaDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaDonHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(162, 162, 162))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(themSanPhamVaoBang)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLoSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                                .addComponent(txtSoLuong)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(xoaSanPham))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonSuaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonXemLichSuBan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(62, 62, 62)))
                            .addComponent(buttonChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(buttonOK))
                            .addComponent(buttonThanhToan, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(85, 85, 85))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonExit)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(themSanPhamVaoBang, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(xoaSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOK)
                    .addComponent(buttonSuaDonHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonThanhToan)
                    .addComponent(buttonXemLichSuBan))
                .addGap(18, 18, 18)
                .addComponent(buttonExit)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDonHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDonHangActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
    // tính tổng tiền và lưu vào textfield    
        int countRow = tableSanPham.getRowCount();
        int countColSoLuong = 4;
        int countcolDonGia =5;
        double tong = 0;
        for (int i = 0; i < countRow; i++) {
            double soLuong = Double.parseDouble(tableSanPham.getValueAt(i, countColSoLuong).toString());
            double donGia = Double.parseDouble(tableSanPham.getValueAt(i, countcolDonGia).toString());
            tong +=soLuong * donGia;
        }
       this.txtTongTien.setText(String.valueOf(tong));
       
    }//GEN-LAST:event_buttonOKActionPerformed

    private void thoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoiGianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thoiGianActionPerformed

    private void buttonThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThanhToanActionPerformed
        // TODO add your handling code here:
        
        //lưu dữ liệu vào database
        DefaultTableModel model = (DefaultTableModel) this.tableSanPham.getModel();
        int rowTable = tableSanPham.getRowCount();
        PreparedStatement stmt;
        PreparedStatement stmt1;
        PreparedStatement stmt2 = null;
        Connection con;
        Connection conn;
        Connection connn;
        
        try {
            con = DBConnect.getConnection();
            String sql ="INSERT INTO chitietdonhang (maDonHang, maSanPham, soLo, tenSanPham,soLuong ,donGia, thanhTien) VALUES (?, ?, ? ,?,?,?,?)";
            stmt = con.prepareStatement(sql);
            for (int i = 0; i < rowTable; i++) {
                String data1 = model.getValueAt(i, 0).toString();
                String data2 = model.getValueAt(i, 1).toString();
                String data3 = model.getValueAt(i, 2).toString();
                String data4 = model.getValueAt(i, 3).toString();
                Object data5 = model.getValueAt(i, 4);
                Object data7 = model.getValueAt(i, 5);
                Object data6 =  model.getValueAt(i, 6);

                stmt.setString(1, data1);
                stmt.setString(2, data2);
                stmt.setString(3, data3);
                stmt.setString(4, data4);
                stmt.setObject(5, data5);
                
                stmt.setObject(6, data7);

                stmt.setObject(7, data6);
                stmt.executeUpdate();
            }
            con.close();
            stmt.close();
        }catch (SQLException ex) {
            Logger.getLogger(ThemPN.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //lưu dữ liệu vào data quanlidonhang.
        try {
            conn  = DBConnect.getConnection();
            String data7 = txtMaDonHang.getText();
            String data8 = thoiGian.getText();
            Object data9 = txtTongTien.getText();
            
            String sql1 ="INSERT INTO quanlidonhang (maDonHang, ngayTaoDonHang , tongTien) VALUES (? ,? ,?)";
            stmt1 = conn.prepareStatement(sql1);
            stmt1.setString(1, data7);
            stmt1.setString(2, data8);
            stmt1.setObject(3, data9);
            stmt1.executeUpdate();
            
            conn.close();
            stmt1.close();
        } catch (SQLException ex) {
            Logger.getLogger(JFTaoDonHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //update lại số lượng hiện có trong cửa hàng.
        try {
            connn = DBConnect.getConnection();
            for (int i = 0; i < rowTable; i++) {
                String data1 = model.getValueAt(i, 1).toString();
                String data2 = model.getValueAt(i, 2).toString();
                Object data3 = model.getValueAt(i, 4);
                String sql = "update sanphamhienco set soLuong = soLuong -"+data3+" where maSanPham='"+data1+"' and soLo ='"+data2+"'";
                stmt2 = connn.prepareStatement(sql);
                stmt2.executeUpdate();
            }
            connn.close();
            stmt2.close();
            JOptionPane.showMessageDialog(rootPane, "Successful update");
        } catch (SQLException ex) {
            System.out.println("looix");
             Logger.getLogger(ThemPN.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //quay trở về trang chủ.
        dispose();
        JFTrangChu jf = new JFTrangChu();
        jf.show();
    }//GEN-LAST:event_buttonThanhToanActionPerformed

    private void themSanPhamVaoBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSanPhamVaoBangActionPerformed

        String maDonHangCheck = null;
        String maSp = txtMaSanPham.getText();
        String soLuong = txtSoLuong.getText();
        String lo = txtLoSanPham.getText();
        String madh = txtMaDonHang.getText();
        
        Statement stmt = null;
        String idSanPhamCheck = null;
        Connection conn = null;
        Connection con = null;
        
        //check 4 dữ liệu nhập vào bị thiếu.
        if(maSp.equals("") || soLuong.equals("") || lo.equals("")||madh.equals("")){
            
            JOptionPane.showMessageDialog(rootPane, "lỗi thiếu dữ liệu!");
            return ;
        }else{
            try {
                    con = DBConnect.getConnection();
                    stmt = con.createStatement();
                    String sql = "SELECT maDonHang FROM chitietdonhang WHERE maDonHang ='"+txtMaDonHang.getText() +"'";
                    ResultSet rs = stmt.executeQuery(sql);
                    while (rs.next()) {
                        maDonHangCheck = rs.getString("maDonHang");
                    }
                    rs.close();
                    stmt.close();
                    con.close();
                    if(madh.equals(maDonHangCheck)){
                        JOptionPane.showMessageDialog(rootPane, "mã đơn hàng đã tồn tại!");
                        return;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ThemPN.class.getName()).log(Level.SEVERE, null, ex);
                }
            try {
                conn =DBConnect.getConnection();
                stmt = conn.createStatement();
                //viet cau lenh sql
                String sql ="SELECT * FROM nhaphang WHERE maSanPham ='"+txtMaSanPham.getText() +"' AND soLo ='"+txtLoSanPham.getText()+"'";
                //xử lí kết quả trả về/.
                ResultSet rs = stmt.executeQuery(sql);
                while (rs.next()) {                    
                    idSanPhamCheck = rs.getString("maSanPham");
                }
                //đóng các hoạt động kết nối với mysql.
                rs.close();
                conn.close();
                stmt.close();
                if (maSp.equals(idSanPhamCheck)) {
                    addSanPham(maSp, lo ,soLuong);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "lỗi sai mã sản phẩm hoặc số lô!");
                    return ;
                }
            } catch (SQLException ex) {
                Logger.getLogger(JFTaoDonHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtMaSanPham.setText(null);
        txtSoLuong.setText(null);
        txtLoSanPham.setText(null);
    }//GEN-LAST:event_themSanPhamVaoBangActionPerformed
//bắt sự kiện click mouse lên row
    private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.tableSanPham.getModel();
        int rowSelect = tableSanPham.getSelectedRow();
        txtMaSanPham.setText((String) model.getValueAt(rowSelect,1));
        txtLoSanPham.setText((String) model.getValueAt(rowSelect,2));
        txtSoLuong.setText((String) model.getValueAt(rowSelect,4));
        
    }//GEN-LAST:event_tableSanPhamMouseClicked

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        JFTrangChu jf = new JFTrangChu();
        jf.show();
        dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void xoaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaSanPhamActionPerformed
        // TODO add your handling code here:
        int rowSelect = tableSanPham.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) this.tableSanPham.getModel();
        if (rowSelect != -1) {
            model.removeRow(rowSelect);
            txtMaSanPham.setText("");
            txtLoSanPham.setText("");
            txtSoLuong.setText("");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn mục muốn thực hiện!");
        }
    }//GEN-LAST:event_xoaSanPhamActionPerformed

    private void buttonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChinhSuaActionPerformed
        // TODO add your handling code here:
        buttonChinhSua.addActionListener(new ActionListener() {
             
            public void actionPerformed(ActionEvent e) {
                int rowSelect = tableSanPham.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();
           
                if (rowSelect != -1) {
                    model.removeRow(rowSelect);
                    themSanPhamVaoBangActionPerformed(e);
                    buttonChinhSua.removeActionListener(this);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn mục muốn thực hiện!");
                    buttonChinhSua.removeActionListener(this);
                }
            }
        });
    }//GEN-LAST:event_buttonChinhSuaActionPerformed

    private void buttonXemLichSuBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXemLichSuBanActionPerformed
        // TODO add your handling code here:
        LichSuBanHang jf = new LichSuBanHang();
        jf.show();
        dispose();
    }//GEN-LAST:event_buttonXemLichSuBanActionPerformed

    private void buttonSuaDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaDonHangActionPerformed
        // TODO add your handling code here:
        JFSuaDonHang jf = new JFSuaDonHang();
        jf.show();
        dispose();
    }//GEN-LAST:event_buttonSuaDonHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTaoDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTaoDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTaoDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTaoDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTaoDonHang().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChinhSua;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonSuaDonHang;
    private javax.swing.JButton buttonThanhToan;
    private javax.swing.JButton buttonXemLichSuBan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JButton themSanPhamVaoBang;
    private javax.swing.JTextField thoiGian;
    private javax.swing.JTextField txtLoSanPham;
    private javax.swing.JTextField txtMaDonHang;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JLabel txtTongTien;
    private javax.swing.JButton xoaSanPham;
    // End of variables declaration//GEN-END:variables
}
