/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlibanhang;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public final class SuaXoaSP extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachSP
     */
    public SuaXoaSP() {
        initComponents();
        hienAllSanPham();
    }
    public  void hienAllSanPham(){
        DefaultTableModel model = (DefaultTableModel) this.tbSanPham.getModel();
        Connection con =null;
        Statement stmt = null;
        try {
            con = DBConnect.getConnection();
            stmt = con.createStatement();
            String sql = "Select * from quanlisanpham";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                rs.getString("maSanPham"),
                rs.getString("tenSanPham"),
                rs.getDouble("donGia"),
                rs.getString("donVi")
                });
            }
            con.close();
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
             Logger.getLogger(SuaXoaSP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        txtTenSanPham = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtDonVi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        buttonChinhSua = new javax.swing.JButton();
        buttonXoa = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        buttonTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Đơn giá: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Đơn vị:");

        txtMaSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTenSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        txtDonVi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Mã sản phẩm: ");

        tbSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Đơn vị"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSanPham);

        buttonChinhSua.setBackground(new java.awt.Color(220, 187, 253));
        buttonChinhSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonChinhSua.setText("Chỉnh sửa");
        buttonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChinhSuaActionPerformed(evt);
            }
        });

        buttonXoa.setBackground(new java.awt.Color(218, 182, 253));
        buttonXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonXoa.setText("Xóa");
        buttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaActionPerformed(evt);
            }
        });

        buttonExit.setBackground(new java.awt.Color(255, 51, 0));
        buttonExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonTimKiem.setBackground(new java.awt.Color(220, 187, 253));
        buttonTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonTimKiem.setText("Tìm");
        buttonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonVi, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtDonGia)
                            .addComponent(txtTenSanPham)
                            .addComponent(txtMaSanPham)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonChinhSua))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(buttonTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExit)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(buttonExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(buttonChinhSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonXoa)
                        .addGap(12, 12, 12)
                        .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        JFQuanLiSanPham jf = new JFQuanLiSanPham();
        jf.show();
        dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.tbSanPham.getModel();
        int rowSelect = tbSanPham.getSelectedRow();
        txtMaSanPham.setText((String) model.getValueAt(rowSelect,0));
        txtTenSanPham.setText((String) model.getValueAt(rowSelect,1));
        txtDonGia.setText(model.getValueAt(rowSelect, 2).toString());
        txtDonVi.setText((String) model.getValueAt(rowSelect,3));
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void buttonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimKiemActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        Statement stmt = null;
        DefaultTableModel model = (DefaultTableModel) this.tbSanPham.getModel();
        //xoa du lieu bang
        for (int i =  tbSanPham.getRowCount()-1; i>=0; i--) {
            model.removeRow(i);
        }
        try {
            con = DBConnect.getConnection();
            stmt = con.createStatement();
            String sql ="Select * from quanlisanpham where maSanPham='"+txtMaSanPham.getText()+"' or tenSanPham ='"+txtTenSanPham.getText()+"'";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                rs.getString("maSanPham"),
                rs.getString("tenSanPham"),
                rs.getDouble("donGia"),
                rs.getString("donVi")
                });
            }
            con.close();
            stmt.close();
            rs.close();
        } catch (SQLException ex) {
            System.out.println("oks");
            Logger.getLogger(SuaXoaSP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonTimKiemActionPerformed

    private void buttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.tbSanPham.getModel();
        Connection con = null;
        PreparedStatement stmt = null;
        int rowSelect = tbSanPham.getSelectedRow();
        //vừa xóa vừa cập nhật  vào trong cơ sở dữ liệu.
        if (rowSelect != -1) {
             model.removeRow(rowSelect);
             //update vào cơ sở dữ liệu.
             try {
                con = DBConnect.getConnection();
                String sql = "delete from quanlisanpham where maSanPham ='"+txtMaSanPham.getText()+"'";
                stmt = con.prepareStatement(sql);
                stmt.executeUpdate();
                con.close();
                stmt.close();
                JOptionPane.showMessageDialog(rootPane, "Xóa sản phẩm thành công.");
                txtMaSanPham.setText("");
                txtTenSanPham.setText("");
                txtDonGia.setText("");
                txtDonVi.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(SuaXoaSP.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Chọn mục muốn thực hiện!");
            return;
        }
    }//GEN-LAST:event_buttonXoaActionPerformed

    private void buttonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChinhSuaActionPerformed
        // TODO add your handling code here:
        Double dongia = (Double.valueOf(txtDonGia.getText()));
        
        DefaultTableModel model = (DefaultTableModel) this.tbSanPham.getModel();
        Connection con = null;
        PreparedStatement stmt = null;
        int rowSelect = tbSanPham.getSelectedRow();
        //xóa ở trên bảng và trong cơ ở dữ liệu
        if (rowSelect != -1) {
             model.removeRow(rowSelect);
             //update vào cơ sở dữ liệu.
             try {
                con = DBConnect.getConnection();
                String sql = "delete from quanlisanpham where maSanPham ='"+txtMaSanPham.getText()+"'";
                stmt = con.prepareStatement(sql);
                stmt.executeUpdate();
                con.close();
                stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(SuaXoaSP.class.getName()).log(Level.SEVERE, null, ex);
            }
             //cập nhật kết quả vừa sửa vào cơ sở dữ liệu
            try {
                con = DBConnect.getConnection();
                String sql1 = "insert into quanlisanpham(maSanPham,tenSanPham,donGia,donVi) values('"+txtMaSanPham.getText()+"' ,'"+txtTenSanPham.getText()+"','"+txtDonGia.getText()+"','"+txtDonVi.getText()+"')";
                
                stmt = con.prepareStatement(sql1);
                stmt.executeUpdate();
                con.close();
                stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(SuaXoaSP.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Chọn mục muốn thực hiện!");
            return;
        }
        //hiển thị lại kq vừa sửa lên bảng
        model.addRow(new Object[]{
        txtMaSanPham.getText(),
        txtTenSanPham.getText(),
        dongia,
        txtDonVi.getText()
        });
        JOptionPane.showMessageDialog(rootPane, "Thành công.");
        txtMaSanPham.setText("");
        txtTenSanPham.setText("");
        txtDonGia.setText("");
        txtDonVi.setText("");
    }//GEN-LAST:event_buttonChinhSuaActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaXoaSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaXoaSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaXoaSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaXoaSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaXoaSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChinhSua;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonTimKiem;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDonVi;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtTenSanPham;
    // End of variables declaration//GEN-END:variables
}
